# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20170522_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pose_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Poses'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='server.Users'),
        ),
    ]
